# Generated by Django 2.2.12 on 2020-09-22 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20200921_1455'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infocontact',
            options={'verbose_name': 'InfoContact', 'verbose_name_plural': 'InfoContacts'},
        ),
    ]
