# Generated by Django 2.2.12 on 2020-09-22 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andreaapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fashion',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
