# Generated by Django 2.2.12 on 2020-09-22 11:34

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('andreaapp', '0002_fashion_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='content',
            field=tinymce.models.HTMLField(null=True, verbose_name='content'),
        ),
    ]
