# Generated by Django 2.2.12 on 2020-09-30 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andreaapp', '0005_fashion_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
