# Generated by Django 2.2.12 on 2020-09-30 11:40

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('andreaapp', '0006_travel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='content',
            field=tinymce.models.HTMLField(null=True, verbose_name='content'),
        ),
    ]
