# Generated by Django 2.2.12 on 2020-09-30 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('andreaapp', '0007_travel_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='categorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorieTravel', to='andreaapp.Categorie'),
        ),
        migrations.AddField(
            model_name='travel',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userCreated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='travel',
            name='tag',
            field=models.ManyToManyField(null=True, related_name='tagTravel', to='andreaapp.Tag'),
        ),
    ]
