# Generated by Django 2.2.12 on 2020-09-30 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andreaapp', '0008_auto_20200930_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='tag',
            field=models.ManyToManyField(related_name='tagTravel', to='andreaapp.Tag'),
        ),
    ]
